### ISSUE TITLE
Navigation bar persists after multiple times resume the app

### ISSUE THREAD

**Issue by mrhieu** [mesmotronic/cordova-fullscreen-plugin#1]
When the app is in resuming state, sometimes the navigation bar doesn't disappear.

**Comment by spythonman** [comment]
+1.

Steps to reproduce:
1) Open the app in fullscreen mode (it works, status bar disapear)
2) Go to home screen using home button of the status bar
3) Resume the app
4) Now the status bar is displayed, and won't disapear until the app is closed and reopened.

**Comment by neilrackett** [comment]
Are you calling `AndroidFullScreen.immersiveMode()` again when the app is resumed?
