### ISSUE TITLE
Need a new release (1.0.1)

### ISSUE THREAD

**Issue by micky2be** [mesmotronic/cordova-fullscreen-plugin#11]
I usually set my dependency with version tag.
Could you please make a new release please.
And perhaps put it on NPM too.

Thanks

**Comment by neilrackett** [comment]
Release 1.0.1 added.

We're in the process of looking at the best way to add this plugin to npm and/or plugman; see #10.

**Comment by micky2be** [comment]
Thanks
For NPM it's pretty easy ;)

**Comment by micky2be** [comment]
Still waiting :(

**Comment by neilrackett** [comment]
Your wait is over: #10
