### ISSUE TITLE
Not work after cordova 3.6.3 upgrade

### ISSUE THREAD

**Issue by mrhieu** [mesmotronic/cordova-fullscreen-plugin#2]
After upgrading cordova to 3.6.3 I can not get this work

**Comment by Phoscur** [comment]
Can't get this to work with Cordova 4.2.0 / Ionic getting
```
TypeError: window.AndroidFullScreen is undefined
onDeviceReady
```
sticking to com.cranberrygame.phonegap.plugin.navigationbar, for now, that seems to work as expected... it uses another mode of export?

**Comment by micky2be** [comment]
Any update?
