### ISSUE TITLE
Safe area

### ISSUE THREAD

**Issue by atix9000** [mesmotronic/cordova-fullscreen-plugin#49]
How to calculate safe area with this plugin? Do i need to use another plugin to do it?

**Comment by neilrackett** [comment]
This plugin does not currently have an explicit method or property for calculating the safe area, although you may be able to select a full screen mode that doesn't cover the notch using `AndroidFullScreen.setSystemUiVisibility(...)` or add the required functionality to the plugin yourself using the [methods described here](https://developer.android.com/develop/ui/views/layout/display-cutout)
