### ISSUE TITLE
what about IOS ??

### ISSUE THREAD

**Issue by ashishsajwan** [mesmotronic/cordova-fullscreen-plugin#8]
this plugin works well for android .. do we have any option for IOS as well ???

**Comment by neilrackett** [comment]
Almost all of the plugin's functionality is Android-specific, so there are no plans to extend it to other platforms at the moment.

For now, I would suggest using it with [cordova-plugin-statusbar](https://github.com/apache/cordova-plugin-statusbar) something like this:

```js
// Full screen
if (!AndroidFullScreen.immersiveMode())
{
    StatusBar.hide();
}
```
